### ISSUE TITLE
Hits returned - fewer than in the VIAF hosted lookup

### ISSUE THREAD

**Issue by ilovan** [cwrc/viaf-entity-lookup#1]
I was testing the GitWriter and noticed that the VIAF entity lookup returned fewer dynamic hits than the VIAF hosted lookup. 

For example, while looking for John Smoke Johnson, I lost all hits by the time I typed "John S", while on the VIAF hosted lookup I got to "John Smok" before I lost all hits. Turns out John Smoke Johnson is not in VIAF but I think more hits during the dynamic lookup than we are getting now could help in cases where the name has multiple variants, foreign spelling or diacritics.

**Comment by SusanBrown** [comment]
Version on CANARIE servers isn't current. James and Andrew have been having difficulties getting it up. No point testing until new build is up.

**Comment by ilovan** [comment]
I conducted a review of the existing Google docs documentation and relevant gitHub repositories and this is what I found and think may be of some use (@jefferya , please have look to make sure I am not referencing anything that I shouldn't)

### Entity lookups as referenced to the NERVE developer 
(various email exchanges):

- getResultFromGeoName - https://github.com/cwrc/CWRC-Dialogs/blob/master/js/cD.js#L3097

- getResultFromGoogleGeocode - https://github.com/cwrc/CWRC-Dialogs/blob/master/js/cD.js#L3116

- getResultFromCWRC - https://github.com/cwrc/CWRC-Dialogs/blob/master/js/cD.js#L3135

- getResultFromVIAF - https://github.com/cwrc/CWRC-Dialogs/blob/master/js/cD.js#L3172

For background information, useful documentation on the VIAF API endpoint can be found on OCLC's Web site at this URL: http://www.oclc.org/developer/develop/web-services/viaf/authority-cluster.en.html

The appropriate GET method constructions for the three types of entities, as well as examples of how to formulate links to individual result set records, are as follows:

* person entities -- example search for "Jane Austen"
http://www.viaf.org/viaf/search?query=local.personalNames+all+%22Jane%20Austen%22&sortKeys=holdingscount&maximumRecords=10&startRecord=1&httpAccept=text/xml
- a link to a selected record from the result set: http://viaf.org/viaf/102333412/

* organization entities -- example search for "United Nations"
http://www.viaf.org/viaf/search?query=local.corporateNames+all+%22United%20Nations%22&sortKeys=holdingscount&maximumRecords=10&startRecord=1&httpAccept=text/xml
- a link to a selected record from the result set: http://viaf.org/viaf/131378718/

* title entities -- example search for "Cosmos"
http://www.viaf.org/viaf/search?query=local.uniformTitleWorks+=%22Cosmos%22&sortKeys=holdingscount&maximumRecords=10&startRecord=1&httpAccept=text/xml
- a link to a selected record from the result set: http://viaf.org/viaf/219468490/

Some code that might help one to interpret the VIAF HTTP GET response: https://github.com/cwrc/CWRC-Dialogs/blob/master/js/cD.js#L3224-L3275


### Re syntax of the get request:

VIAF - term should surrounded by double quotation marks(") otherwise a search for a one term name produces no results (e.g. sappho).
local.personalNames+all+"sappho" NOT local.personalNames+all+sappho

(I believe this is applicable to the current VIAF lookup as well since searching for "John"' produces no VIAF results)

### Re possible auto suggest 
(not sure if this is what you were using or not, James) 
 viaf uses http://viaf.org/viaf/AutoSuggest
callback is the function to be called with the results

### Github issues of possible relevance:

- https://github.com/cwrc/CWRC-Dialogs/issues/80

- https://github.com/cwrc/CWRC-Dialogs/issues/70

- https://github.com/cwrc/CWRC-Dialogs/issues/69

**Comment by jchartrand** [comment]
Those are the VIAF calls I am using (although I am also using a call for place names with the ‘local.geographicNames’ restriction)

I’m not sure why you aren’t getting VIAF results for ‘John’ - I get them (although some are strange).

And, yes, that is the VIAF auto suggest uri I had been using, but am not now, since it isn’t clear to me how to combine both auto suggest and full results for several different entity sources (see https://github.com/cwrc/CWRC-WriterBase/issues/12)

I’m not sure what is to be done with this issue?

**Comment by ilovan** [comment]
For the record, VIAF returns still seem insufficient, but it looks like this an ongoing issue with VIAF (see CWRC-Dialogs issues listed above)

**Comment by ilovan** [comment]
Sample TEI tetter:

1. Selected "John"
2. Hit "Tag person"
3. These are the results returned: 

![capture 2](https://user-images.githubusercontent.com/6600070/32855976-a51bdae2-ca00-11e7-88f2-209c6a55bb23.PNG)

Tested on a PC in Chrome.

Could it have something to do with surrounding the term with quotation marks in the get request ? (see above references to VIAF api documentation)


I believe we need to find a way to improve the quality of the VIAF results returned. This issue is a place to store relevant comments, test results, links to documentation, decisions on how to move forward, etc.

**Comment by jchartrand** [comment]
Very strange.  This is what I get:



What server are you using, browser, etc.?

**Comment by ilovan** [comment]
Can't see your screenshot in the above comment. 

Chrome PC (as mentioned above)
Using the CWRC-Writer @ http://208.75.74.217

**Comment by jchartrand** [comment]
I've just now pasted the image link into the earlier comment, but here it is again:

<img width="640" alt="pastedgraphic-3" src="https://user-images.githubusercontent.com/547165/32856798-d8f9d1ee-ca13-11e7-8b4d-ad75791e3fdc.png">

I'm doing this in Chrome on a Mac.  I'll try on Windows, but it really shouldn't matter.  Do you, by any chance, have a slow connection?

What happens if you re-trigger the search using the button at the bottom of the popup?

Also, how are you selecting John?  Dbl-click on word?  selecting range from first letter to last?  Anything else that might be different?

We should probably move this to a new issue (that is assigned to me), since I think it is a different problem.  

And I'd suggest reassigning the current issue to someone else other than me, unless we can clarify specifically what I'm to do next.  Otherwise, it will probably fall out of view.

**Comment by ilovan** [comment]
I can't reproduce it anymore, odd. It happened twice, once when I first mentioned it and once when I took the screenshot.

I think I selected the letter range . When I reloaded using the search again button I got the same results as you did. 

Do yo still want to move this to a separate issue just to keep track of it?

I will assign Susan to the current issue and label it as "decision needed" because something needs to be done with the VIAF results (the way they shape up right now, even in the example we've been using, they are unusable). I kept you as an assignee as well, since you will need to be involved in the conversation.
Is this suitable for you?

**Comment by jchartrand** [comment]
> On Nov 15, 2017, at 3:47 PM, Mihaela Ilovan <notifications@github.com> wrote:
> 
> I can't reproduce it anymore, odd. It happened twice, once when I first mentioned it and once when I took the screenshot.
> 
> I think I selected the letter range . When I reloaded using the search again button I got the same results as you did.
> 
> Do yo still want to move this to a separate issue just to keep track of it?
> 
> 
No, I suggest we wait until it surfaces again.
> I will assign Susan to the current issue and label it as "decision needed" because something needs to be done with the VIAF results (the way they shape up right now, even in the example we've been using, they are unusable). I kept you as an assignee as well, since you will need to be involved in the conversation.
> Is this suitable for you?
> 
> 
Yes.

**Comment by jchartrand** [comment]
One more thing I’d add is that the VIAF results for vague terms like John do return strange results, but maybe that’s not surprising given how vague ‘John’ is.   Even on the VIAF search page (https://viaf.org/viaf/search?query=local.names+all+%22john%22&sortKeys=holdingscount&recordSchema=BriefVIAF) the second result when searching for John is Maimonides, Moses, 1135-1204. ‎ Were you getting better results from some other page?

In contrast, a name like Brynjulf Bull returns a single exact match (when searching VIAF from the CWRC-Writer)

And a search for something even slightly more concrete than John, say John Smith, returns ostensibly more meaningful results, like those below (although the ‘undefined’ result below is clearly a problem and I’d suggest creating a GitHub issue for that since it is a specific problem that I can fix).  

But, I wonder how much we can really do for a name like ‘John Smith’ without allowing for other criteria (e.g., DOB) which VIAf doesn’t however support.  We could allow for ‘more’ results to be shown (or Next 10, etc.), but even then for some names (like John Smith), if the person isn’t well known and their name is common, it could be difficult to find them.

**Comment by SusanBrown** [comment]
I agree that vague terms are pretty useless and that we can't do a lot about them. That said, I suspet we will need to try to tune the searches as we're able. I simply couldn't find Elizabeth I in Orlando recently (using the old lookups on beta).

If I understand what I'm being asked, then I suggest that for now we:

1. ensure that people can put in a URI manually. I think this was specified already.
2. Add a "insert tag minus identifier" button to allow someone to insert the tag only if they can't find their person etc. in the lists.
3. plan to test for this further internally and then with users to get feedback
3. if it is easier than making what lists are open by default configurable, instead have all lists open and let them close the ones they don't find useful, and then persist what lists they keep open for the rest of the session

**Comment by ilovan** [comment]
1. We talked about this in the context of the entity lookups incorporated into the entity creation forms 
(i.e. for the same as relationship). Let's agree to implemented across all entity lookup dialogs.
2. I propose the following design tweaks:
![entity lookup jpeg](https://user-images.githubusercontent.com/6600070/32965968-8d73302a-cb95-11e7-8565-a6cd94e3f0ff.png)


4. I support having all lists open and letting users close the ones they don't find useful, and then persist what lists they keep open for the rest of the session.

**Comment by SusanBrown** [comment]
"Other" button looks good.

I think that "Tag w/o entity linking", or if space permits preferably "Tag without entity linking" would be a better way of indicating that no entity would be created.

Do you disagree that we should have the other lookups open by default? I admit that it might be overmuch (we will be adding Orlando and REED).

**Comment by ilovan** [comment]
@SusanBrown ,

Do we want separate lookups for the Orlando and REED entities?
I thought we agreed on having only one CWRC lookup that would gather all entities hosted by cwrc and return the logo of the project they belonged to (CWRC, Orlando or REED). CAN you please confirm either way?

**Comment by SusanBrown** [comment]
I don’t recall agreeing to this. I can see pros and cons to each.


On Dec 4, 2017, at 4:57 PM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/susanbrown> ,

Do we want separate lookups for the Orlando and REED entities?
I thought we agreed on having only one CWRC lookup that would gather all entities hosted by cwrc and return the logo of the project they belonged to (CWRC, Orlando or REED). CAN you please confirm either way?

**Comment by susanirenebrown** [comment]
Didn’t mean to send so fast. 

Do we have a sense of whether the course you’re suggesting would be easier to implement? If so, let’s go with it. If not, I’d like to consult with the other projects.

cheers,
Susan

**Comment by ilovan** [comment]
So we have the following options actually, in terms of  searching the entities within CWRC:

1. Unified lookup for all entities (Orlando, REED, CWRC) - each result returned - with project logo displayed to far right in the list; 

    a. every CWRC user can link to any entity, no matter the source of the entity and the user's editing/viewing rights for that source project (this would mean that all entity collection would be visible to all CWRC members (and also to the public, if the projects want their EAPs to be viewable by everyone)

    b. CWRC users can link only to the CWRC entities and the entities belonging to a project they are members of (this would mean that the project-specific entity collections would have to be either filtered out in the lookup results, even if visible to all CWRC members (and also to the public, if the projects want their EAPs to be viewable by everyone)in any other contexts, or restricted for viewing under all circumstances to the members of the project they belong to.

2. Separate lookups for each entity collection (CWRC, REED, Orlando)

    a. same as 1.a above (every user will see all three CWRC-supported lookups)

    b. same as 1.b. above (users will only see the lookups they have access to)


@jchartrand , do you foresee any technical difficulties with any of these approaches? (we agreed to have the entities splint into separate collections by source (CWRC, Orlando, REED)


Once a decision has been reached, I will create a separate issue for this (completely different subject than the title suggests)

__________________________________________

Incidentally though, the issue in the title still persists:


These are the results returned for a "Bertrand Russell" lookup in the old entity dialogs in the version of CWRC Writer integrated into the CWRC production environment:

<img width="394" alt="screen shot 2018-01-30 at 10 51 34 am" src="https://user-images.githubusercontent.com/6600070/35582336-c9b4c90e-05ab-11e8-82ef-1c9ce5b93147.png">


These are the results for the same VIAF lookup in dev GitWriter:

<img width="785" alt="screen shot 2018-01-30 at 8 55 47 am" src="https://user-images.githubusercontent.com/6600070/35582378-e4a6b29a-05ab-11e8-92ad-9b7ef0f2c660.png">

**Comment by ilovan** [comment]
Conversation with Susan: 
# Decisions

- All EAPs are viewable by everyone
- We'll go with 1.a

**Comment by jchartrand** [comment]
> On Jan 30, 2018, at 12:55 PM, Mihaela Ilovan <notifications@github.com> wrote:
> 
> So we have the following options actually, in terms of searching the entities within CWRC:
> 
> Unified lookup for all entities (Orlando, REED, CWRC) - each result returned - with project logo displayed to far right in the list;
> 
> a. every CWRC user can link to any entity, no matter the source of the entity and the user's editing/viewing rights for that source project (this would mean that all entity collection would be visible to all CWRC members (and also to the public, if the projects want their EAPs to be viewable by everyone)
> 
> b. CWRC users can link only to the CWRC entities and the entities belonging to a project they are members of (this would mean that the project-specific entity collections would have to be either filtered out in the lookup results, even if visible to all CWRC members (and also to the public, if the projects want their EAPs to be viewable by everyone)in any other contexts, or restricted for viewing under all circumstances to the members of the project they belong to.
> 
> Separate lookups for each entity collection (CWRC, REED, Orlando)
> 
> a. same as 1.a above (every user will see all three CWRC-supported lookups)
> 
> b. same as 1.b. above (users will only see the lookups they have access to)
> 
> @jchartrand <https://github.com/jchartrand> , do you foresee any technical difficulties with any of these approaches? (we agreed to have the entities splint into separate collections by source (CWRC, Orlando, REED)
> 
> 
1a certainly sounds easiest.  I can’t foresee any difficulties, but there are of course sure to be some challenges once the rubber hits the road.
> Once a decision has been reached, I will create a separate issue for this (completely different subject than the title suggests)
> 
> Incidentally though, the issue in the title still persists:
> 
> 
Since this is a bit different than the original issue, which I think we agreed was possibly due differences between the hosted VIAF and their web service version, could we create a new issue for this, and I’ll look into it with whatever priority you assign?  A new issue with just the clear images you provided will also make it easier (quicker) to understand the problem later.  The new results are clearly incorrect though.

**Comment by lucaju** [comment]
@ilovan is this still an issue?

**Comment by ilovan** [comment]
nope - that I can tell. will close.
