### ISSUE TITLE
VIAF labels often showing and appearing as "undefined"

### ISSUE THREAD

**Issue by jchartrand** [cwrc/viaf-entity-lookup#2]
@SusanBrown commented on [Tue Jan 23 2018](https://github.com/cwrc/CWRC-PublicEntityDialogs/issues/15)

![image](https://user-images.githubusercontent.com/545952/35287178-be8e3d66-002f-11e8-94ba-594f87c3f37e.png)

**Comment by jchartrand** [comment]
I'll move this to QA once the new dev setup is working properly.

**Comment by ilovan** [comment]
this seems to be fixed, so I am moving it to "DeployToProd"

**Comment by ilovan** [comment]
seems to be fixed in Prod Git-Writer and dev-06
