### ISSUE TITLE
url used to fetch full preview of a result is http, but should be https

### ISSUE THREAD

**Issue by jchartrand** [cwrc/viaf-entity-lookup#3]

**Comment by jchartrand** [comment]
So what's going on here is that we show a popup when someone clicks on a result in an entity lookup, e.g.,

![image](https://user-images.githubusercontent.com/547165/35651732-b9a016be-06ae-11e8-82c7-33f7a5be0195.png)

And, as in the screenshot above, the popup is not showing any content, because we are trying to get the content for the popup from an HTTP url (which isn't allowed from a page that was itself loaded with HTTPS).  The underlying problem is that the HTTP url (from which to get the content for the popup) comes from the original result we got from VIAF (or wikidata, getty, dbpedia).  And they are all http urls.  

So, we could rewrite the uris to use HTTPS, before making the request.  This is a bit tied up in how the four CWRC entity lookups (for viaf, getty, wikidata, and dbpedia) return results to the CWRC-PublicEntityDialogs, and so rather than rewrite the urls from within the CWRC-PublicEntityDialogs (which is where the code to show the popup exists), I'd probably add another property to the result returned from the entity lookups themselves, and call the property something like UriForDisplay, which would hold the rewritten uri.   rewriting the wikidata and viaf uris just amounts to changing the http to https.  For dbpedia and getty, I'll have to rewrite them to make the call through the cwrc proxy.

I'd hope this all goes relatively smoothly.  Shall I go ahead?

**Comment by SusanBrown** [comment]
Sounds like the way to go, particularly since you don’t mention any alternatives. Please proceed.
