### ISSUE TITLE
Fix security vulnerability

### ISSUE THREAD

**Issue by ilovan** [cwrc/viaf-entity-lookup#4]
https://github.com/cwrc/viaf-entity-lookup/network/dependencies

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/viaf-entity-lookup/commit/977958dca1aabfd2b2c947a12e1a2790f0e7fa78
https://github.com/cwrc/viaf-entity-lookup/commit/ddf1fc773e7f6e49f20ac6ddfa72f0c4d74e5bdd
