### ISSUE TITLE
SSL certificate warning in Chrome

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/viaf-entity-lookup#6]
The warning message is:
The SSL certificate used to load resources from https://viaf.org will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by SusanBrown** [comment]
I don’t understand. I didn’t think we were using Symantec, which is what this seems to be about at a glance. James, could you weigh in?



On Apr 17, 2018, at 5:14 PM, Andrew <notifications@github.com<mailto:notifications@github.com>> wrote:


The warning message is:
The SSL certificate used to load resources from https://viaf.org<https://viaf.org/> will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.
