### ISSUE TITLE
VIAF results preview broken in all CWRC_Writer instances

### ISSUE THREAD

**Issue by ilovan** [cwrc/viaf-entity-lookup#9]
![image.png](https://images.zenhubusercontent.com/5a5e621f4b5806bc2bc2ff7d/61a50880-dfbb-4195-8d68-46e1f1436252)

**Comment by ilovan** [comment]
Decision: Duplicate Work from the GeoNames results handling

**Comment by ajmacdonald** [comment]
e496de72930915fa2bbce2e09db3c07843f36fa6

**Comment by ilovan** [comment]
confirmed in both production environments
